# Autogenerated wrapper script for GRAMPC_jll for x86_64-w64-mingw32
export libgrampc_julia

JLLWrappers.@generate_wrapper_header("GRAMPC")
JLLWrappers.@declare_library_product(libgrampc_julia, "libgrampc_julia.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libgrampc_julia,
        "bin\\libgrampc_julia.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
